export default[
    {
        path: '/',
        name: 'Layout',
        component: ()=>import('../views/LayOut.vue'),
        redirect:'/index',
        children:[
            {
                path:'/index',//首页
                name:'index',
                component:()=>import('../views/Index/IndexHome.vue')
            },
            {
                path:'/orders/list',
                name:'orders_list',
                component:()=>import('../views/Orders/OrdersList.vue'),
                meta:{bread:["订单管理","订单列表"]}//面包屑导航数据
            },
            {
                path:'/waybill/in',
                name:'waybill_in',
                component:()=>import('../views/waybill/WaybillIn.vue'),
                meta:{bread:["运单管理","运单录入"]}//面包屑导航数据
            },
            {
                path:'/waybill/list',
                name:'waybill_list',
                component:()=>import('../views/waybill/WaybillList.vue'),
                meta:{bread:["运单管理","运单列表"],keepAlive:true}//面包屑导航数据
            },
            {
                path:'/waybill/list/detail',
                name:"list_detail",
                component:()=>import('../views/waybill/DetailVue.vue'),
                meta:{bread:["运单管理","运单列表"]}
            },
            {
                path:'/depart/data',
                name:'depart_data',
                component:()=>import('../views/depart/DepartData.vue'),
                meta:{bread:["发车管理","发车数据单"],keepAlive:true}//面包屑导航数据
            },
            {
                path:'/depart/data/detail',
                name:'depart_data_detail',
                component:()=>import('../views/depart/DepartDetail.vue'),
                meta:{bread:["发车管理","发车数据单"],keepAlive:true}//面包屑导航数据
            },
            {
                path:'/carrier/list',
                name:'carrier_list',
                component:()=>import('../views/carrier/CarrierList.vue'),
                meta:{bread:["承运商管理","承运商列表"]}//面包屑导航数据
            },
            {
                path:'/carrier/trucks',
                name:'carrier_trucks',
                component:()=>import('../views/carrier/CarrierTrucks.vue'),
                meta:{bread:["承运商管理","车辆列表"]}//面包屑导航数据
            },
            {
                path:'/carrier/drivers',
                name:'carrier_drivers',
                component:()=>import('../views/carrier/CarrierDrivers.vue'),
                meta:{bread:["承运商管理","承运司机列表"]}//面包屑导航数据
            },
            {
                path:'/customer/list',
                name:'customer_list',
                component:()=>import('../views/customer/CustomerList.vue'),
                meta:{bread:["客户管理","客户列表"]}//面包屑导航数据
            },
            {
                path:'/finacial/customer',
                name:"finacial_customer",
                component:()=>import('../views/finacial/FinacialCustomer.vue'),
                meta:{bread:["财务管理","客户对账单"]}//面包屑导航数据
            },
            {
                path:'/finacial/carrier',
                name:"finacial_carrier",
                component:()=>import('../views/finacial/FinacialCarrier.vue'),
                meta:{bread:["财务管理","承运商对账单"]}//面包屑导航数据
            },
            {
                path:'/finacial/driver',
                name:'finacial_driver',
                component:()=>import('../views/finacial/FinacialDriver.vue'),
                meta:{bread:["财务管理","承运司机列表"]}//面包屑导航数据
            },
            {
                path:'/personal',
                name:'personal',
                component:()=>import('../views/personal/PersonalVue.vue'),
                meta:{bread:["个人中心"]}//面包屑导航数据
            }
        ]
      },
      {
        path:'/login',
        name:'Login',
        component:()=>import('../views/LoginVue.vue')
      },
]